# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c5VKaHQ1cmtYaSFcf0TC-PcTSgBz1wtw
"""

pip install streamlit

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

st.title("K-Means Clustering From Scratch")

uploaded_file = st.file_uploader("Upload CSV", type=["csv"])

if uploaded_file:

    data = pd.read_csv(uploaded_file)

    st.write(data.head())

    # Run your KMeans implementation here

    st.success("Clustering Completed")

