# -*- coding: utf-8 -*-
"""K-Means.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rkCwMjyfQiVxsRJpdYXwp8jbspqllZHV
"""

import pandas as pd

from google.colab import files

uploaded = files.upload()

pd.read_excel("/content/customer_spending.xlsx")

df=pd.read_excel("/content/customer_spending.xlsx")

df.info()

df.isnull()

df.groupby('Customer_ID')['Annual_Spending'].sum().sort_values(ascending=False).head(10)

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Select relevant features for clustering
X = df[['Annual_Spending', 'Order_Count']]

# Scale the features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)

print(X_scaled_df.head())

# Determine optimal number of clusters using the Elbow Method
wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42, n_init='auto')
    kmeans.fit(X_scaled)
    wcss.append(kmeans.inertia_)

import matplotlib.pyplot as plt
plt.figure(figsize=(10, 6))
plt.plot(range(1, 11), wcss, marker='o', linestyle='--')
plt.title('Elbow Method For Optimal K')
plt.xlabel('Number of Clusters (K)')
plt.ylabel('WCSS')
plt.xticks(range(1, 11))
plt.grid(True)
plt.show()

print("The Elbow method plot suggests an optimal K where the decrease in WCSS (Within-Cluster Sum of Squares) starts to level off.")
print("Based on the plot, we can visually inspect the 'elbow' point to choose a suitable number of clusters.")

# Apply K-Means clustering (choosing k=3 as an example from the elbow method, adjust if needed)
k_optimal = 4 # This value can be adjusted after inspecting the elbow plot
kmeans = KMeans(n_clusters=k_optimal, init='k-means++', random_state=42, n_init='auto')
df['Cluster'] = kmeans.fit_predict(X_scaled)

print(f"K-Means clustering applied with {k_optimal} clusters.")
print("Data with cluster assignments head:")
print(df.head())

# Analyze cluster characteristics
cluster_summary = df.groupby('Cluster')[['Annual_Spending', 'Order_Count']].mean()
print("Cluster Summary (Mean values for Annual_Spending and Order_Count):")
print(cluster_summary)

# Visualize the clusters

import seaborn as sns
plt.figure(figsize=(12, 8))
sns.scatterplot(x='Annual_Spending', y='Order_Count', hue='Cluster', data=df, palette='viridis', s=100, alpha=0.7)
plt.title(f'Customer Segments based on Annual Spending and Order Count (K={k_optimal})')
plt.xlabel('Annual Spending')
plt.ylabel('Order Count')
plt.grid(True)
plt.legend(title='Cluster')
plt.show()

# Calculate the Silhouette Score
silhouette_avg = silhouette_score(X_scaled, df['Cluster'])
print(f"The Silhouette Score for the {k_optimal} clusters is: {silhouette_avg:.3f}")

